/**
 * Clearly-labeled SAMPLE report for the `/analyze/demo` showcase route.
 *
 * This is static placeholder content so visitors can preview the report
 * layout. It must NEVER be presented as retrieved evidence — the Analyze
 * page renders a "Sample report" badge whenever this fixture is shown.
 */
import type { VerificationResponse } from "./types";

export const SAMPLE_REQUEST_ID = "demo";

export const SAMPLE_RESPONSE: VerificationResponse = {
  request_id: "demo",
  processed_at: "2026-09-01T12:00:00+00:00",
  input_type: "text",
  input_summary: {
    title: null,
    publisher: null,
    author: null,
    published_at: null,
    domain: null,
    url: null,
  },
  claims: [
    {
      claim_id: "claim_demo_1",
      claim_text: "A new study shows that urban green spaces improve mental health within weeks.",
      score: 82,
      classification: "Mostly Supported",
      summary:
        "Most retrieved sources agree with the claim, with one important context gap to keep in view.",
      supporting_evidence: [
        {
          evidence_id: "ev_demo_1",
          title: "What the latest data tells us about the claim",
          url: "https://example.com/sample/reuters-data",
          publisher: "Reuters",
          published_at: "2026-08-30T09:00:00+00:00",
          snippet: "Sample excerpt: independent reporting on the study's headline finding.",
          stance: "SUPPORTING",
          rationale: "Sample rationale.",
          is_primary_source: false,
          source_reliability: "high",
        },
        {
          evidence_id: "ev_demo_2",
          title: "Primary document: findings and methodology",
          url: "https://example.com/sample/research-archive",
          publisher: "National Research Archive",
          published_at: "2026-08-28T09:00:00+00:00",
          snippet: "Sample excerpt: the primary document's methodology section.",
          stance: "SUPPORTING",
          rationale: "Sample rationale.",
          is_primary_source: true,
          source_reliability: "high",
        },
      ],
      contradicting_evidence: [
        {
          evidence_id: "ev_demo_3",
          title: "The context missing from the viral version",
          url: "https://example.com/sample/factcheck-context",
          publisher: "FactCheck.org",
          published_at: "2026-08-27T09:00:00+00:00",
          snippet: "Sample excerpt: the timeframe detail could not be confirmed.",
          stance: "CONTRADICTING",
          rationale: "Sample rationale.",
          is_primary_source: false,
          source_reliability: "high",
        },
      ],
      neutral_evidence: [],
      fact_checks: [],
      source_analysis: [],
      duplicate_clusters: [],
      score_breakdown: [
        { factor: "evidence_agreement", label: "Evidence agreement", contribution: 24, detail: "Sample detail." },
        { factor: "source_quality", label: "Source quality", contribution: 18, detail: "Sample detail." },
        { factor: "independent_sources", label: "Independent sources", contribution: 16, detail: "Sample detail." },
        { factor: "fact_checks", label: "Fact-check evidence", contribution: 12, detail: "Sample detail." },
        { factor: "official_evidence", label: "Official evidence", contribution: 8, detail: "Sample detail." },
        { factor: "transparency", label: "Transparency", contribution: 4, detail: "Sample detail." },
      ],
      verification_gaps: [
        {
          gap_type: "unverified_detail",
          description:
            "Sources support the general benefit, but none of the primary material confirms that the effect appears within weeks. Treat that detail as unverified rather than false.",
        },
      ],
      evidence_reasoning: {
        summary: "Sample reasoning: the core relationship is supported; the timeframe is uncertain.",
        key_findings: [],
        supporting_findings: [],
        contradicting_findings: [],
        important_discrepancies: ["Sample: timeframe wording differs across sources."],
        source_observations: [],
        independence_observations: [],
        fact_check_observations: [],
        verification_gaps: [],
        uncertainty: "MEDIUM",
        reasoning_steps: [],
        limitations: ["Sample report — not based on retrieved evidence."],
        ai_used: false,
        provider: null,
        model: null,
        fallback_used: true,
      },
      independent_source_count: 4,
      total_evidence_count: 3,
      retrieved_evidence: [],
    },
  ],
  overall_score: 82,
  overall_classification: "Mostly Supported",
  overall_summary:
    "The available evidence supports the core claim, but the exact timeframe is not consistently established across sources.",
  limitations: ["Sample report — not based on retrieved evidence."],
  report: {
    report_id: "demo-report",
    generated_at: "2026-09-01T12:00:00+00:00",
    methodology_version: "v1.0",
    input_summary: {
      input_type: "text",
      headline: null,
      source_url: null,
      text_length: 76,
      claim_count: 1,
      verification_timestamp: "2026-09-01T12:00:00+00:00",
    },
    overall_result: {
      score: 82,
      classification: "Mostly Supported",
      summary:
        "The available evidence supports the core claim, but the exact timeframe is not consistently established across sources.",
    },
    executive_summary:
      "Sample summary: most retrieved sources agree with the claim, with one important context gap to keep in view.",
    claims: [
      {
        claim_id: "claim_demo_1",
        claim_text: "A new study shows that urban green spaces improve mental health within weeks.",
        claim_type: "SCIENTIFIC",
        importance: "HIGH",
        score: 82,
        classification: "Mostly Supported",
        is_insufficient_evidence: false,
        summary: "Most retrieved sources agree with the claim, with one important context gap to keep in view.",
        evidence_summary: {
          total_retrieved: 3,
          supporting_count: 2,
          contradicting_count: 1,
          neutral_count: 0,
          insufficient_count: 0,
          independent_source_count: 4,
          duplicate_count: 0,
          syndicated_count: 0,
          fact_check_count: 0,
        },
        supporting_evidence: [
          {
            evidence_id: "ev_demo_1",
            title: "What the latest data tells us about the claim",
            publisher: "Reuters",
            url: "https://example.com/sample/reuters-data",
            publication_date: "2026-08-30T09:00:00+00:00",
            snippet: "Sample excerpt: independent reporting on the study's headline finding.",
            stance: "SUPPORTING",
            relevance: 0.9,
            cluster_id: null,
            independence_status: "LIKELY_INDEPENDENT",
            source_category: "news_media",
            source_reliability: "high",
          },
          {
            evidence_id: "ev_demo_2",
            title: "Primary document: findings and methodology",
            publisher: "National Research Archive",
            url: "https://example.com/sample/research-archive",
            publication_date: "2026-08-28T09:00:00+00:00",
            snippet: "Sample excerpt: the primary document's methodology section.",
            stance: "SUPPORTING",
            relevance: 0.9,
            cluster_id: null,
            independence_status: "LIKELY_INDEPENDENT",
            source_category: "academic",
            source_reliability: "high",
          },
        ],
        contradicting_evidence: [
          {
            evidence_id: "ev_demo_3",
            title: "The context missing from the viral version",
            publisher: "FactCheck.org",
            url: "https://example.com/sample/factcheck-context",
            publication_date: "2026-08-27T09:00:00+00:00",
            snippet: "Sample excerpt: the timeframe detail could not be confirmed.",
            stance: "CONTRADICTING",
            relevance: 0.7,
            cluster_id: null,
            independence_status: "LIKELY_INDEPENDENT",
            source_category: "fact_checker",
            source_reliability: "high",
          },
        ],
        neutral_evidence: [],
        insufficient_evidence: [],
        fact_checks: [],
        discrepancies: [],
        verification_gaps: [
          "Sources support the general benefit, but none of the primary material confirms that the effect appears within weeks. Treat that detail as unverified rather than false.",
        ],
        source_analysis: [],
        independence_analysis: null,
        score_breakdown: null,
        ai_reasoning: null,
        limitations: [],
      },
    ],
    evidence_summary: {
      total_retrieved: 3,
      supporting_count: 2,
      contradicting_count: 1,
      neutral_count: 0,
      insufficient_count: 0,
      independent_source_count: 4,
      duplicate_count: 0,
      syndicated_count: 0,
      fact_check_count: 0,
    },
    citations: [],
    limitations: ["Sample report — not based on retrieved evidence."],
  },
};
