"""Config package initialization."""

from backend.config.settings import settings
from backend.config.scoring_config import (
    SCORING_WEIGHTS,
    CLASSIFICATION_THRESHOLDS,
    MIN_INDEPENDENT_SOURCES,
    MIN_CLASSIFIED_EVIDENCE_ITEMS,
    DUPLICATE_SIMILARITY_THRESHOLD,
    MAX_RESULTS_PER_NEWS_PROVIDER,
    MAX_RESULTS_PER_WEB_PROVIDER,
    MAX_FACTCHECK_RESULTS,
    CACHE_TTL_SECONDS,
)

__all__ = [
    "settings",
    "SCORING_WEIGHTS",
    "CLASSIFICATION_THRESHOLDS",
    "MIN_INDEPENDENT_SOURCES",
    "MIN_CLASSIFIED_EVIDENCE_ITEMS",
    "DUPLICATE_SIMILARITY_THRESHOLD",
    "MAX_RESULTS_PER_NEWS_PROVIDER",
    "MAX_RESULTS_PER_WEB_PROVIDER",
    "MAX_FACTCHECK_RESULTS",
    "CACHE_TTL_SECONDS",
]
